version: "3"

services:
    front:
        build:
            context: "./nginx"
        image: chi-hod-front
        ports:
            - "80:80"
        container_name: chnginx
        restart: unless-stopped
        expose:
            - "80"
    back:
        build:
            context: "./go-server"
        image: chi-hod-back
        container_name: chgo
        expose:
            - "10234"
            - "10235"
        restart: unless-stopped
        depends_on:
            - front
    mysqlch:
        container_name: mysqlch
        image: mysql:latest
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=cheihod
            - MYSQL_ROOT_PASSWORD=wasdqert
        expose:
            - "3306"
volumes:
    db:
        driver: local
